name: Sync
on: [push]

jobs:
  sync_ios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: corona-warn-app/cwa-app-ios
          ref: development
      - run: echo SSH_PUB_KEY > ~/.ssh/id_ed25519.pub
      - run: echo SSH_KEY > ~/.ssh/id_ed25519
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git push -f git@github.com:cosee/cwa-app-ios.git development
    env:
      SSH_KEY: ${{ secrets.IOS_SSH_KEY }}
      SSH_PUB_KEY:  ${{ secrets.IOS_SSH_PUB_KEY }}
